name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_API: ${{ secrets.DOCKERHUB_USERNAME }}/employee-api
  IMAGE_OPERATOR: ${{ secrets.DOCKERHUB_USERNAME }}/employee-operator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: anjalikfti24
          password: Annufti@12

      - name: Build and push employee-api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: anjalikfti24/employee-api:1.2

      - name: Build and push employee-operator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.operator
          push: true
          tags: anjalikfti24/employee-operator:1.2

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      NAMESPACE: employee
    steps:
      - name: crc Setup
        run: |
          crc setup
          crc start
          eval $(crc oc-env)
      - name: Login to OpenShift
        run: |
          oc login "https://api.crc.testing:6443" --token="sha256~XWpGPyC3qF8dB8QWTpW0EGwqVUlZrD5pv0CQbp38EPA" --insecure-skip-tls-verify
      - name: Set project
        run: oc project $NAMESPACE

      - name: Apply CRD
        run: oc apply -f crd.yaml

      - name: Deploy operator
        run: |
          echo "🛠️  Deploying operator..."
          oc apply -f operator-deployment.yaml -n $NAMESPACE

      - name: Deploy application
        run: |
          echo "🛠️  Deploying application..."
          oc apply -f deployment.yaml -n $NAMESPACE

      - name: Delete route if available
        run: |
          echo "Delete route if available"
          oc delete route employee-api -n $NAMESPACE || true

      - name: Wait for 5 minutes
        run: sleep 300

      - name: Expose service
        run: |
          echo "🌐 Exposing service..."
          oc expose service employee-api -n $NAMESPACE
