name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_API: ${{ secrets.DOCKERHUB_USERNAME }}/employee-api
  IMAGE_OPERATOR: ${{ secrets.DOCKERHUB_USERNAME }}/employee-operator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push employee-api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ env.IMAGE_API }}:latest

      - name: Build and push employee-operator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.operator
          push: true
          tags: ${{ env.IMAGE_OPERATOR }}:latest

  # Optional: Deploy to OpenShift
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install oc CLI
        run: |
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz"
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/
      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify
      - name: Set project
        run: oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: Update employee-api deployment image
        run: |
          oc set image deployment/employee-api employee-api=${{ env.IMAGE_API }}:1.1
      - name: Update employee-operator deployment image
        run: |
          oc set image deployment/employee-operator operator=${{ env.IMAGE_OPERATOR }}:1.1
